[package]
name = "ring"
version = "0.1.0"
authors = ["Nawo Mbechezi mlanawo@mbechezi.kemeter.io"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.1"
tokio = { version = "1.20", features = ["full"] }
log = "0.4.0"
env_logger = "0.8.3"
shiplift = { git = "https://github.com/softprops/shiplift" }
yaml-rust = "0.4"
clap = "2.33.3"
clokwerk = "0.4.0"
chrono = "0.4"
uuid = { version = "1.4.1", features = ["v4"] }
serde_rusqlite = "0.33.1"
rusqlite = { version = "0.29.0", features = [ ] }
ureq = { version = "2.3.0", features = ["json"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8.1"
local-ip-address = "0.5.5"
cli-table = "0.4"
axum = { version = "0.7.4" }
axum-extra = { version = "0.9.2", features = ["typed-header"] }
tower = { version = "0.4", features = ["util", "timeout"] }
tower-http = { version = "0.5.1", features = ["add-extension", "trace"] }
axum-macros = "0.4.1"
rust-argon2 = "2.0.0"
refinery = { version = "0.8", features = [ "rusqlite-bundled" ] }
regex = "1.6.0"
serde_yaml = "0.9.25"
tempdir = "0.3.7"

[dev-dependencies]
axum-debug = "0.3.3"
