version: "3.8"

services:
    ring:
        image: rust:1.53
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./:/srv/project
        working_dir: /srv/project

    tikv:
        image: tikv/tikv
